@startuml
class Purchase {
    + Purchase()
    + Purchase(purchaseId:int, username:string, customerNameSurname:string, applicationUser:ApplicationUser, deliveryAddress:string, purchaseDate:DateTime, purchaseItems:IList<PurchaseItem>, paymentMethod:PaymentMethodTypes)
    + Purchase(username:string, customerNameSurname:string, applicationUser:ApplicationUser, deliveryAddress:string, purchaseDate:DateTime, purchaseItems:IList<PurchaseItem>, paymentMethod:PaymentMethodTypes)
    + Id : int <<get>> <<set>>
    + TotalPrice : decimal <<get>> <<set>>
    + DeliveryAddress : string <<get>> <<set>>
    + CustomerUserName : string <<get>> <<set>>
    + CustomerNameSurname : string <<get>> <<set>>
}
class "IList`1"<T> {
}
Purchase --> "PurchaseDate" DateTime
Purchase --> "ApplicationUser" ApplicationUser
Purchase --> "PurchaseItems<PurchaseItem>" "IList`1"
Purchase --> "PaymentMethod" PaymentMethodTypes
@enduml
