@startuml

left to right direction
!include .\\Movie.puml


!include .\\RentalItem.puml
!include .\\Rental.puml




Movie "Movie"  o---  "0..* RentalItems"  RentalItem

Rental "Rental"  o---  "0..* RentalItems"  RentalItem


hide Genre

hide Purchase
hide PurchaseItem
hide methods
hide PaymentMethodTypes
hide ApplicationUser

@enduml
