namespace AppForMovies.API.Models
{
    public class Rental
    {
        public Rental()
        {
        }
        public Rental(string customerUserName, string customerNameSurname, ApplicationUser applicationUser, string deliveryAddress, DateTime rentalDate, PaymentMethodTypes paymentMethod, DateTime rentalDateFrom, DateTime rentalDateTo, IList<RentalItem> rentalItems)
        {
            TotalPrice = rentalItems.Sum(ri => ri.PriceForRenting * (rentalDateTo - rentalDateFrom).Days);

            //autogenerated
            RentalDateFrom = rentalDateFrom;
            RentalDateTo = rentalDateTo;
            RentalDate = rentalDate;
            DeliveryAddress = deliveryAddress;
            CustomerUserName = customerUserName;
            CustomerNameSurname = customerNameSurname;
            ApplicationUser = applicationUser;
            RentalItems = rentalItems;
            PaymentMethod = paymentMethod;
        }

        public int Id { get; set; }

        public double TotalPrice { get; set; }=10.2;

        public DateTime RentalDate { get; set; }=DateTime.Today;

        public DateTime RentalDateFrom { get; set; }=DateTime.Today;
        public DateTime RentalDateTo { get; set; }=DateTime.Today;


        [DataType(System.ComponentModel.DataAnnotations.DataType.MultilineText)]
        [Display(Name = "Delivery Address")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please, set your address for delivery")]
        public string DeliveryAddress { get; set; }="Albacete";

        public string CustomerUserName { get; set; }="peter.jackson@uclm.es";

        public string CustomerNameSurname { get; set; }="Peter Jackson";
        [Display(Name = "Payment Method")]
        public PaymentMethodTypes PaymentMethod { get; set; }=PaymentMethodTypes.CreditCard;

        public IList<RentalItem> RentalItems { get; set; }= new List<RentalItem>();

        public ApplicationUser ApplicationUser { get; set; }=new ApplicationUser();
    }

    public enum PaymentMethodTypes
    {
        CreditCard,
        PayPal,
        Cash
    }
}
